version: '3.1'
services:
   rabbitmq:
    image: rabbitmq:3-management
    restart: always
    container_name: rabbitmq
    networks:
      - new_network
    ports:
      - '5672:5672'
   auth-data:
    image: postgres:latest
    restart: always
    container_name: auth-database
    environment:
      POSTGRES_USER: roixy
      POSTGRES_PASSWORD: mysecret
      POSTGRES_DB: Auth
    networks:
      - new_network
    ports:
      - '5432:5432'
    volumes:
      - auth-data:/var/lib/postgresql/data
   community-data:
    image: postgres:latest
    restart: always
    container_name: community-database
    environment:
      POSTGRES_USER: roixy
      POSTGRES_PASSWORD: mysecret
      POSTGRES_DB: Community
    networks:
      - new_network
    ports:
      - '5433:5432'
    volumes:
      - community-data:/var/lib/postgresql/data
   message-data:
    image: postgres:latest
    restart: always
    container_name: message-database
    environment:
      POSTGRES_USER: roixy
      POSTGRES_PASSWORD: mysecret
      POSTGRES_DB: Message
    networks:
      - new_network
    ports:
      - '5434:5432'
    volumes:
      - message-data:/var/lib/postgresql/data
volumes:
  auth-data:
  community-data:
  message-data:
networks:
  new_network: